#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>

# src code references
source='
  cppcheck.cpp
  ../matrix.h ../matrix.cpp
  ../redirect_io.h
  '

cppcheck ${source} -x c++ --enable=all --verbose --suppressions-list=suppressions.txt --check-config