#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>

# src code references
source='
  cppcheck.cpp
  ../redirect_io.h
  ../matrix.h
  ../matrix.cpp
  '

cppcheck ${source} --language=c++ --std=c++20 --inconclusive --enable=all --error-exitcode=1 --verbose --suppressions-list=suppressions.txt